name: Scrape and Sum Tables – 24f2001499@ds.study.iitm.ac.in

on:
  push:
    paths:
      - script.js
  workflow_dispatch:  # ✅ Allow manual runs

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright
        run: npm install playwright

      - name: Run scraper – 24f2001499@ds.study.iitm.ac.in
        run: |
          node script.js
