name: Scrape and Sum Tables – 24f2001499@ds.study.iitm.ac.in

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install playwright

      - name: Run scraper – 24f2001499@ds.study.iitm.ac.in
        run: node scrape.js
