name: Scrape and Sum Tables – 24f2001499@ds.study.iitm.ac.in

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Chromium dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxss1 libxcomposite1 libxrandr2 libasound2 libpangocairo-1.0-0

      - name: Install Playwright with browsers
        run: |
          npm init -y
          npm install playwright
          npx playwright install

      - name: Run scraper – 24f2001499@ds.study.iitm.ac.in
        run: node scrape.js
